{{- $kubefledgedWebhookSvc := (include "kubefledged.webhookServiceName" . ) -}}
{{- $kubefledgedWebhookSvcFullName := ( printf "%s.%s.svc" $kubefledgedWebhookSvc .Release.Namespace )  -}}
{{- $altNames := list $kubefledgedWebhookSvc $kubefledgedWebhookSvcFullName  -}}
{{- $ca := genCA (include "kubefledged.webhookServiceName" . | quote) 365 -}}
{{- $cert := genSignedCert $kubefledgedWebhookSvc nil $altNames 365 $ca -}}
---

apiVersion: v1
data:
  ca.crt: '{{ $ca.Cert | b64enc }}'
  tls.crt: '{{ $cert.Cert | b64enc }}'
  tls.key: '{{ $cert.Key | b64enc }}'
kind: Secret
metadata:
  name: {{ include "kubefledged.webhookServerCertSecretName" . | quote }}
  labels:
    {{ include "kubefledged.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubefledged.validatingWebhookName" . }}
  labels:
    {{ include "kubefledged.labels" . | nindent 4 }}  
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
webhooks:
  - name: validate-image-cache.kubefledged.io
    admissionReviewVersions: ["v1beta1", "v1"]
    timeoutSeconds: 1
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        namespace: {{ .Release.Namespace | quote }}
        name: {{ include "kubefledged.webhookServiceName" . }}
        path: "/validate-image-cache"
        port: {{ .Values.webhookService.port }}
      caBundle: '{{ $ca.Cert | b64enc }}'
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["kubefledged.io"]
        apiVersions: ["v1alpha2"]
        resources: ["imagecaches"]
        scope: "Namespaced"
